on:
  push:
    branches:
      - main
      - master
      - dev
      - community_data
  pull_request:
    branches:
      - main
      - master

name: check-coverage

jobs:
  check-coverage:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name:  Test coverage
        run: covr::codecov()
        shell: Rscript {0}
